logging:
  level:
    com.johney.fourth: INFO
    org.springframework.boot.context: INFO
server:
  compression:
    enabled: true
  port: 8080
  servlet: 
    context-path: /starter
springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
    info:
      title: 
      description: Api Base Application Docs.
      version: 1.0
    base-package: com.johney.fourth
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        db: starter
        uri: http://starter_influxdb:8086
spring:
  messages:
    basename: i18n/messages
  cache:
    type: redis
  data:
    mongodb:
      host: starter_mongodb
      port: 27017
      database: starter
  rabbitmq:
    host: starter_rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    writeQueue: rabbit-queue
    readQueue: rabbit-dead-queue
    exchange: rabbit-exchange
    connection-timeout: 9000

