version: "3.7"
services:
  app:
    image: @project.artifactId@:@project.version@
    ports: 
      - 8080:8080
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
    depends_on:
      
      
      - redis
      
    networks:
      - backend
      - frontend
    links:
      
      
      - redis:redis
      
  
  
  redis:
    image: redis:5.0.4-alpine
    ports: 
      - 6379:6379
    networks:
      - backend
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
  
  
networks:
  backend:
  frontend:
volumes:
    
    
    redisdata:
    
    